### ISSUE TITLE
建议使用show启动移仓助手RolloverTool

### ISSUE THREAD

**Issue by noranhe** [vnpy/vnpy_ctastrategy#13]
原帖链接：
https://www.vnpy.com/forum/topic/30047-jian-yi-shi-yong-showqi-dong-yi-cang-zhu-shou-rollovertool?page=1#pid53416

**Comment by vnpy** [comment]
1. 改为show会导致dialog对象被立即回收，无法弹出对话框
2. exec只是让图形界面停住不处理其他部分，而非阻塞了事件驱动引擎（后台逻辑不受影响）
