### ISSUE TITLE
策略参数优化时需要一个进度或者时间

### ISSUE THREAD

**Issue by sowans** [vnpy/vnpy_ctastrategy#21]
策略参数优化时需要一个deap优化算法的进度，或者时间。

**Comment by vnpy** [comment]
目前穷举优化算法已经实现基于tqdm的进度输出（在Jupyter环境下可见）。

遗传优化算法由于其多进程调度由DEAP库内部管理，尝试后无法在内部插入tqdm实现进度输出功能。
