### ISSUE TITLE
删除策略以后，只会删除cta_strategy_setting.json而不会删除cta_strategy_data.json里的数

### ISSUE THREAD

**Issue by kkqy** [vnpy/vnpy_ctastrategy#27]
strategy_engine.remove_strategy("xxxxx")
调用remove_strategy以后，只有cta_strategy_setting.json里的相应的数据被清理了，但是保存变量的cta_strategy_data.json里的数据没被清理。
这会导致下次如果新建一样名字的策略，会加载之前的数据。这是故意这么设计的吗？为什么呢
从语义来说，既然是删除了策略，就应该把保存的变量也清理干净，就像删除了文件，总不能创建新的同名文件还会残留之前老文件的内容吧？

论坛帖子URL：https://www.vnpy.com/forum/topic/31619-shan-chu-ce-lue-yi-hou-zhi-hui-shan-chu-cta-strategy-setting-jsoner-bu-hui-shan-chu-cta-strategy-data-jsonli-de-shu-ju

**Comment by vnpy** [comment]
已经修改，感谢反馈
