### ISSUE TITLE
加载策略的时候会把 TargetPosTemplate 也加载进来

### ISSUE THREAD

**Issue by kkqy** [vnpy/vnpy_ctastrategy#28]
TargetPosTemplate只是一个模板，按道理不应该加载为策略
同时，我自己也封装了一些Template作为某些策略的基类，按道理这些都只是模板，而不应该直接当作策略使用。

**Comment by kkqy** [comment]
https://github.com/vnpy/vnpy_ctastrategy/issues/28

**Comment by vnpy** [comment]
已修复，感谢反馈
