### ISSUE TITLE
可变对象在类实例化时不会重复创建，但单策略运行在多品种时需要对同一个类进行多次实例化，如何修改或避免？

### ISSUE THREAD

**Issue by lanceyliao** [vnpy/vnpy_ctastrategy#39]
https://github.com/vnpy/vnpy_ctastrategy/blob/1c31a8c73021de552921184725f8f834371386f5/vnpy_ctastrategy/template.py#L16

在Python中，可变对象在类实例化时不会重复创建，这意味着它们在类的多次实例化中是共享的。这与不可变对象（如整数、字符串等）的行为不同，不可变对象在每次实例化时都会创建一个新的对象。

以下是一个简单的例子，说明了可变对象在类实例化中的共享特性：

```
class MutableObject:
    shared_list = []

    def add_item(self, item):
        self.shared_list.append(item)

# 实例化两个对象
obj1 = MutableObject()
obj2 = MutableObject()

# 在第一个对象上添加一个元素
obj1.add_item(1)

# 第二个对象也会受到影响，因为它们共享同一个可变对象
print(obj2.shared_list)  # 输出 [1]
```

在这个例子中，shared_list 是一个可变的类级别属性。当我们在 obj1 上添加一个元素时，shared_list 发生了变化，而 obj2 也受到了影响，因为它们都共享同一个列表对象。

这种共享特性对于某些用途可能是有用的，但在某些情况下，它也可能导致上述提到的问题，如内存占用过高、重复初始化和对象状态混乱。因此，在设计类时，我们需要注意对象的可变性，并确保适当地使用可变和不可变对象，以避免潜在的问题。

**Comment by vnpy** [comment]
策略类下定义的参数和变量，仅支持str/int/float/bool四种基础数据类型（不可变对象）。

所有可变对象的成员变量（list/dict/set等）定义，请放置到对象构造函数__init__下即可。

**Comment by lanceyliao** [comment]
“所有可变对象的成员变量（list/dict/set等）定义，请放置到对象构造函数__init__下即可。”
那么parameters: list = [] 需要移动，请更新移动方式。

**Comment by vnpy** [comment]
parameters和variables是属于模板类的特殊变量，不是给用户自己定义的
