### ISSUE TITLE
实盘换月可能部分成交、单腿成交，应维护未成交手数、增加撤未成交单功能

### ISSUE THREAD

**Issue by lanceyliao** [vnpy/vnpy_ctastrategy#47]
https://github.com/vnpy/vnpy_ctastrategy/blob/a7e55082f9e3d0c7dec058117384ba47cf2e9f3d/vnpy_ctastrategy/ui/rollover.py#L259

**Comment by vnpy** [comment]
无法确认Issue具体指向的内容，如果对于大量持仓的高性能移仓换月有需求，可以考虑VeighNa Elite版，其中提供了完善的异步模式价差移仓执行算法。
