### ISSUE TITLE
variables重复添加target_pos？

### ISSUE THREAD

**Issue by lanceyliao** [vnpy/vnpy_ctastrategy#48]
https://github.com/vnpy/vnpy_ctastrategy/blob/049a1e32ad57e6d169d97a4fb5bbfac000a770c2/vnpy_ctastrategy/strategies/multi_signal_strategy.py#L150

上面这里是不是重复了？下面有append。
如果去掉上面的，图形界面里变量会正常显示target_pos吗？

https://github.com/vnpy/vnpy_ctastrategy/blob/049a1e32ad57e6d169d97a4fb5bbfac000a770c2/vnpy_ctastrategy/template.py#L393

**Comment by noranhe** [comment]
已修复https://github.com/vnpy/vnpy_ctastrategy/pull/49
