### ISSUE TITLE
load_strategy_class_from_folder不能识别linux目录下的策略文件

### ISSUE THREAD

**Issue by sailorgege** [vnpy/vnpy_ctastrategy#5]
bug说明：pathname没有区分windows及linux/Mac OS，导致非linux环境下，不能找到strategies目录下的策略文件
修正：pathname需要区分是否为windows环境
示例：
import platform
platform_name: str = platform.system().lower()
if platform_name == 'windows':
    pathname: str = str(path) + f"\\*.{suffix}"
else:
    pathname: str = str(path) + f"/*.{suffix}"

**Comment by wwdd23** [comment]
mac 环境
正好也发现这个问题, 查到先自己手工将
.pyenv/versions/3.8.10/lib/python3.8/site-packages/vnpy_ctastrategy/engine.py

修改为 :
 for suffix in ["py", "pyd", "so"]:
            #pathname: str = str(path) + f"\\*.{suffix}"
            pathname: str = str(path) + f"/*.{suffix}"
            for filepath in glob(pathname):
                filename: str = Path(filepath).stem
                name: str = f"{module_name}.{filename}"
                self.load_strategy_class_from_module(name)

**Comment by sailorgege** [comment]
> mac 环境
> 正好也发现这个问题, 查到先自己手工将
> .pyenv/versions/3.8.10/lib/python3.8/site-packages/vnpy_ctastrategy/engine.py
> 
> 修改为 :
> for suffix in ["py", "pyd", "so"]:
> #pathname: str = str(path) + f"\_.{suffix}" pathname: str = str(path) + f"/_.{suffix}"
> for filepath in glob(pathname):
> filename: str = Path(filepath).stem
> name: str = f"{module_name}.{filename}"
> self.load_strategy_class_from_module(name)

是的，mac也是linux内核，所以也会有这个问题。
我是判断了一下平台，非windows的平台都用“/”来连接路径。

**Comment by noranhe** [comment]
已修复
