### ISSUE TITLE
slippage  计算问题

### ISSUE THREAD

**Issue by szshower** [vnpy/vnpy_ctastrategy#53]
https://github.com/vnpy/vnpy_ctastrategy/blob/8d657cfd4ec9493ae36da45f9e2807294ca596d5/vnpy_ctastrategy/backtesting.py#L1067

# slippage 需要乘以 pricetick
 self.slippage += trade.volume * size * slippage * pricetick

**Comment by vnpy** [comment]
slippage参数是具体的滑点价格，而不是多少【跳（pricetick）】
