### ISSUE TITLE
建议把线性年化收益计算方式 改为 复利增长的年化收益计算方式

### ISSUE THREAD

**Issue by szshower** [vnpy/vnpy_ctastrategy#57]
https://github.com/vnpy/vnpy_ctastrategy/blob/1125ae953b6721f45ecfd7c212f91abddcaaa6c6/vnpy_ctastrategy/backtesting.py#L389

```
import math

annual_return: float = (math.pow(end_balance / self.capital, 240 / total_days) - 1)*100
```

**Comment by vnpy** [comment]
CTA策略主要应用于期货等带有杠杆的金融合约上交易，对于这些品种只要账户级别的资金没有被用满，就可以很容易的通过仓位调整来影响整体账户级别的收益率。

因此对于这类策略的回测，不像股票截面多头选股类的策略更在乎复利增长的情况（没有杠杆），而是更在乎在交易风险度不变的情况下（例如仓位保持一致），累计盈亏金额的变动情况（而不是账户的收益率情况）。
