### ISSUE TITLE
策略类中代表仓位的pos变量为小数的时候存在误差，使得DoubleMaStrategy案例中的if self.pos == 0:语句变得不适用

### ISSUE THREAD

**Issue by wuliehan** [vnpy/vnpy_ctastrategy#58]
问题：
在币圈，因为仓位、买卖数量允许采用小数，策略类不可避免的会给pos赋值float类型，但是float类型的计算是存在误差的，例如：0.1+0.2==0.3为假，这就导致先买0.1个币，再买0.2个币，再卖0.3个币后，剩余仓位不为0。这样的话if self.pos == 0:就不能匹配仓位为空这个条件。
解决方案：
一、采用decimal类型替代float类型，它能精确表示十进制小数，常用于金融领域，缺点是损失性能
二、每次对pos加减完后，调用round_to进行四舍五入，缺点是到底四舍五入到第几位需要根据交易标的来决定，不通用
三、用整数模拟定点小数，缺点也是精确到第几位小数需要根据交易标的来决定，不通用
四、用abs函数计算pos和对比值的差，根据结果是否小于一个很小的值来判定是否真的等于，缺点是增加策略编写者的负担，虽然可以用自定义函数覆盖掉“==”运算符，但是容易留下难以察觉的bug
个人倾向于第一个方案。

**Comment by vnpy** [comment]
VeighNa官方团队从2022年起，已经不再提供crypto相关功能支持，有这块需求可以去看看其他团队的项目：https://github.com/veighna-global/vnpy_evo
