### ISSUE TITLE
基类CtaTemplate的load_bar方法的interval参数有默认值并不合理

### ISSUE THREAD

**Issue by wuliehan** [vnpy/vnpy_ctastrategy#62]
`def load_bar(
        self,
        days: int,
        interval: Interval = Interval.MINUTE,
        callback: Callable = None,
        use_database: bool = False
    ) -> None:`
以上是基类CtaTemplate的load_bar方法签名，其中interval的默认参数设置为分钟并不合理，且很多案例都用了默认值，用户在使用的时候容易造成误解。比如运用到日线的时候，很容易以为self.load_bar(10)的意思是自动载入10天的日线bar，但其实不会。
以下两种方案应该会更好：
1.没有默认值，必须由用户输入
2.用户一般会通过engine设置周期，可自动获取engine中设置的周期当作这里的默认值

**Comment by vnpy** [comment]
日线级别的低精度回测不是CtaStrategy主要针对的策略场景（尽管支持了），如果主要是做这类量化策略建议可以直接使用pandas向量化回测来实现即可。
