### ISSUE TITLE
函数`cross_stop_order()`的long_cross_price和short_cross_price设置反了

### ISSUE THREAD

**Issue by zhaorui20005** [vnpy/vnpy_ctastrategy#64]
基于代码理解以及文档提示:
有如下解释,即
```
**buy**：买入开仓（Direction：LONG，Offset：OPEN）

**sell**：卖出平仓（Direction：SHORT，Offset：CLOSE）

**short**：卖出开仓（Direction：SHORT，Offset：OPEN）

**cover**：买入平仓（Direction：LONG，Offset：CLOSE）
```
那么我们单看平空(cover)的代码:
```
if self.mode == BacktestingMode.BAR:
            long_cross_price = self.bar.high_price

for stop_order in list(self.active_stop_orders.values()):
            # Check whether stop order can be triggered.
            long_cross: bool = (
                stop_order.direction == Direction.LONG
                and stop_order.price <= long_cross_price
            )
```
对于stop单的Direction为LONG,即买入平仓操作,即cover. 那么本质上还是买入动作,他的long_cross应该和函数`cross_limit_order()`里面的long_cross_price设置以及long_cross应该一致,这块我觉得应该是写反了.

对于short_cross_price,也同样存在相同的问题.

**Comment by vnpy** [comment]
买入方向的停止单，是当价格向上突破价格时候被触发，然后追进去买。

限价单，择时当价格向下跌破价格时候被触发，然后在交易所内直接成交。

**Comment by zhaorui20005** [comment]
对于cross_limit_order()函数买入的限价单,是做多的开单.这快应该没有问题.
因为,对于上一个限价单多单买入,判断在当前BAR是否能够成交,就看是否大于当前BAR最低价格,这块的long_cross_price设定为low_price,实际成交价格取trade_price = min(order.price, long_best_price)也完全正确,有可能开盘就成交,也有可能开盘不成交,那就是order的价格.


但对于cross_stop_order()函数,本质上stop单也是**限价单**.

或者说对于cross_stop_order()函数的long_cross的理解是平多,那么这里判断的Direction应该是SHORT,因为对于做多的STOP单,其方向是SHORT. 而代码却是
```
long_cross: bool = (
                stop_order.direction == Direction.LONG
                and stop_order.price <= long_cross_price
            )
```
从价格设置,比较符合平多的设定,但是Direction.LONG 让人费解.
为了验证,于是参考active_stop_orders的填入的代码:
我参考的是atr_rsi_atr_rsi_strategy代码,其中有两处STOP=true的代码,分别是:
```
#参考CtaTemplate类,有四种操作,分别是buy(做多Direction.LONG),sell(平多Direction.SHORT),short(做空Direction.SHORT),cover(平空Direction.LONG)

self.sell(long_stop, abs(self.pos), stop=True)对应Direction.SHORT
self.cover(short_stop, abs(self.pos), stop=True)对应Direction.LONG.
```

所以,stop_order.direction = Direction.LONG就是对应平空,函数cross_stop_order()代码应该是**平多**.
```
long_cross: bool = (
                stop_order.direction == Direction.SHORT
                and stop_order.price <= long_cross_price
            )
```

**Comment by vnpy** [comment]
您可以看一下比如CME交易所的条件单是怎么个运行原理，国内市场交易所没有提供条件单功能，所以我们通过本地模拟 + 触发后的超价限价单来实现，但是撮合规则依然接近前面的条件单。
