### ISSUE TITLE
如果在子线程使用roll_over, 因为直接调用了 QTextEdit 的append函数，会报错。

### ISSUE THREAD

**Issue by BillyZhangGuoping** [vnpy/vnpy_ctastrategy#8]
子线程使用roll_over中进行移仓，因为直接调用了 QTextEdit 的append函数，这个时候就会出现下面的错误：
QObject::connect: Cannot queue arguments of type 'QTextCursor'
(Make sure 'QTextCursor' is registered using qRegisterMetaType().)

代码：
    def write_log(self, text: str) -> None:
        """"""
        now = datetime.now()
        text = now.strftime("%H:%M:%S\t") + text
        self.log_edit.append(text)

修改使用定义信号，改为信号槽
log_signal: QtCore.pyqtSignal = QtCore.pyqtSignal(str)

        def __init__
        ...
        self.log_signal.connect(self.log_txt_append)
        ...

	def write_log(self, text: str) -> None:
		""""""
		now = datetime.now()
		text = now.strftime("%H:%M:%S\t") + text
		self.main_engine.write_log(text)
		self.log_signal.emit(text)

	def log_txt_append(self,text):
		self.log_edit.append(text)
		self.log_edit.moveCursor(QtGui.QTextCursor.End)

**Comment by vnpy** [comment]
感谢反馈，我们来修复下

**Comment by vnpy** [comment]
我们查了下代码，目前移仓功能在设计上就是让用户从图形界面点击调用的（也就是主线程发起），需要用户在移仓过程中关注相关细节，并不建议在其他线程中（比如通过事件或者脚本）直接调用，所以暂时不做修改。
