### ISSUE TITLE
在返回成交信息很多时候，sync_strategy_data写入卡住

### ISSUE THREAD

**Issue by BillyZhangGuoping** [vnpy/vnpy_ctastrategy#9]
在ctaEngine 中 的process_trade_event，如在开盘时候挂单成交策略较多，挂单成交信息返回较多且散时，其中的sync_strategy_data 写入variables到json文件会卡住，没有报错信息，但是有策略没有更新，虽然内存中pos持仓正确，如果突然重启发现variables错误。

可以考虑使用更新到数据库，有缓冲机制；或者thread写入json file使用单独线程

**Comment by vnpy** [comment]
sync_strategy_data属于文件读写类操作，如果有错误操作系统会抛出异常。

variables错误建议检查策略变量中，是否包含了int/float/str/bool以外的数据类型。

**Comment by xuxin3101** [comment]
这不是卡主，这个是因为并发问题导致的不可重复读的问题，这里需要加锁处理一下

**Comment by xinyundao** [comment]
卡住的问题出现在频繁的写文件，建议将修改内存数据和数据落盘分为两个阶段执行。
